apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-c4vj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-c4vj@sha256:cbb865202a4cdd32f0f1cf62799120f9b26f633fbe0ce670e4a3c0cd3240ea49
        name: my-nodejs
        resources: {}
status: {}
